- id: '1773992047364'
  alias: Test
  description: Test og udvikling af automation
  triggers: []
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: climate.is_on
        target:
          entity_id: climate.home_heat_pump
        options:
          behavior: any
          for: 00:00:00
      sequence: []
  mode: single
