###############################################################################
# Global or system wide sensors
#
# Start in column 1 of the file with a hyphen, like:
# - platform: template
#   sensors:
#     thermestat etc.
###############################################################################
- platform: file
  name: home_meter_reading_electricity
  unique_id: DB5412AC-1D45-4301-BE8B-0114698ED4C0
  device_class: energy
  state_class: total_increasing
  file_path: /data/meter_reading_electricity.csv
  value_template: >
    {% set lines = value.split('\n') %} 
    {% set last = lines | reject('equalto','') | list | last %}
    {{ last.split(',')[1] | float }}
  attribute_templates:
    readings_json: >
      {% set lines = value.split('\n') | reject('equalto','') | list %}
      {% set items = [] %}
      {% for l in lines %}
        {% set parts = l.split(',') %}
        {% set items = items + [ {'timestamp': parts[0], 'value': parts[1]|float} ] %}
      {% endfor %}
      {{ items | tojson }}